### ISSUE TITLE
Address isnt clickable for meetups

### ISSUE THREAD

**Issue by heyahharissa** [TampaBayDesigners/tampabaydesigners#30]
im gonna try to make a pull req but who knows

**Comment by ryan-parag** [comment]
I fixed this so the address on the dynamic event page is clickable to a simple Google Maps page.

I couldn't figure out why the dynamic pages weren't working on Netlify after updating all of the packages, so I switched the hosting to Vercel. Let me know if this is working for you: [Example event page](https://www.tampabay.design/events/3830f5c2-372f-4bf5-8a5f-62bde77979fa)
